// #7 받는 데이터
import 'package:ai_project/Login/kakao_login.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';


class Autogenerated {
   List<DietList> dietList;

  Autogenerated({ this.dietList});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['dietList'] != null) {
      //dietList = new List<DietList>();
      json['dietList'].forEach((v) {
        dietList.add(new DietList.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.dietList != null) {
      data['dietList'] = this.dietList.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class DietList {
   int diet_id;
   String user_id;
   int meal;
   String created_at;
   List<FoodInfo> food_info;
   int cal;
   String img_path;


  DietList({ this.diet_id,  this.user_id,  this.meal,  this.created_at,  this.food_info,  this.cal,  this.img_path});

  DietList.fromJson(Map<String, dynamic> json) {
    diet_id = json['diet_id'];
    user_id = json['user_id'];
    meal = json['meal'];
    created_at = json['created_at'];
    food_info = json['food_info'];
    cal = json['cal'];
    img_path = json['img_path'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['diet_id'] = this.diet_id;
    //data['user_id'] = KakaoLoginState.user_id;
    data['meal'] = this.meal;    
    data['created_at'] = this.created_at;
    data['food_info'] = this.food_info;
    data['cal'] = this.cal;
    data['img_path'] = this.img_path;
    return data;
  }
}

class FoodInfo{
   int no;
   int cal;
   String name;
   int amount;

  FoodInfo({ this.no,  this.cal,  this.name,  this.amount});

  FoodInfo.fromJson(Map<String, dynamic> json){
    no = json['no'];
    cal = json['cal'];
    name = json['name'];
    amount = json['amount'];
  
  }

   Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['no'] = this.no;
    data['cal'] = this.cal;
    data['name'] = this.name;    
    data['amount'] = this.amount;
    return data;
  }

}

