// #7 받는 데이터
import 'package:ai_project/Login/kakao_login.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';


class Autogenerated {
  late List<DietList> dietList;

  Autogenerated({required this.dietList});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['dietList'] != null) {
      //dietList = new List<DietList>();
      json['dietList'].forEach((v) {
        dietList.add(new DietList.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.dietList != null) {
      data['dietList'] = this.dietList.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class DietList {
  late int diet_id;
  late String user_id;
  late int meal;
  late String created_at;
  late List<FoodInfo> food_info;
  late int cal;
  late String img_path;


  DietList({required this.diet_id, required this.user_id, required this.meal, required this.created_at, required this.food_info, required this.cal, required this.img_path});

  DietList.fromJson(Map<String, dynamic> json) {
    diet_id = json['diet_id'];
    user_id = json['user_id'];
    meal = json['meal'];
    created_at = json['created_at'];
    food_info = json['food_info'];
    cal = json['cal'];
    img_path = json['img_path'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['diet_id'] = this.diet_id;
    //data['user_id'] = KakaoLoginState.user_id;
    data['meal'] = this.meal;    
    data['created_at'] = this.created_at;
    data['food_info'] = this.food_info;
    data['cal'] = this.cal;
    data['img_path'] = this.img_path;
    return data;
  }
}

class FoodInfo{
  late int no;
  late int cal;
  late String name;
  late int amount;

  FoodInfo({required this.no, required this.cal, required this.name, required this.amount});

  FoodInfo.fromJson(Map<String, dynamic> json){
    no = json['no'];
    cal = json['cal'];
    name = json['name'];
    amount = json['amount'];
  
  }

   Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['no'] = this.no;
    data['cal'] = this.cal;
    data['name'] = this.name;    
    data['amount'] = this.amount;
    return data;
  }

}

